#!/usr/bin/env bash
# scripts/production-install.sh — Drupal install from production artifact
#
# Designed for the release branch artifact where:
#   - vendor/ is already present (no composer install needed)
#   - settings.local.php does NOT exist yet (generated here)
#   - No demo content, no dev settings, Redis ON from the start
#
# Run inside the PHP container:
#   docker compose -f docker/production-compose.yml exec -T php \
#     bash /var/www/html/scripts/production-install.sh
#
# Or via scripts/deploy.sh --setup (called automatically)

set -euo pipefail
DRUPAL_ROOT="/var/www/html/docroot"
VENDOR_BIN="/var/www/html/vendor/bin"
SITE_URL="${SITE_URL:-https://sityos.com}"
ADMIN_USER="${DRUPAL_ADMIN_USER:?'DRUPAL_ADMIN_USER env var is required'}"
ADMIN_PASS="${DRUPAL_ADMIN_PASS:?'DRUPAL_ADMIN_PASS env var is required'}"
ADMIN_EMAIL="${DRUPAL_ADMIN_EMAIL:?'DRUPAL_ADMIN_EMAIL env var is required'}"

echo "════════════════════════════════════════════════════════"
echo "  Sityos — Production Install Script"
echo "════════════════════════════════════════════════════════"

# ─── Step 0: Generate production settings.local.php ──────────────────────────
echo ""
echo "▶ Step 0/6: Generating production settings.local.php..."
SETTINGS_LOCAL="${DRUPAL_ROOT}/sites/default/settings.local.php"

cat > "${SETTINGS_LOCAL}" << 'SETTINGS_EOF'
<?php

/**
 * @file
 * Production settings — generated by scripts/production-install.sh.
 * NOT committed to git. Regenerated only on --setup.
 */

declare(strict_types=1);

// ─── Database ─────────────────────────────────────────────────────────────────
$databases['default']['default'] = [
  'driver'    => 'mysql',
  'database'  => getenv('DB_NAME')  ?: 'sityos_automate',
  'username'  => getenv('DB_USER')  ?: 'sityos_automate_user',
  'password'  => getenv('DB_PASS')  ?: 'S1ty0s4ut0m4t3#2026',
  'host'      => getenv('DB_HOST')  ?: 'mysql',
  'port'      => getenv('DB_PORT')  ?: '3306',
  'prefix'    => '',
  'collation' => 'utf8mb4_general_ci',
  'namespace' => 'Drupal\\mysql\\Driver\\Database\\mysql',
  'autoload'  => 'core/modules/mysql/src/Driver/Database/mysql/',
];

// ─── Redis connection ─────────────────────────────────────────────────────────
$settings['redis.connection']['interface'] = 'PhpRedis';
$settings['redis.connection']['host']      = 'redis';
$settings['redis.connection']['port']      = 6379;

// ─── Production performance ───────────────────────────────────────────────────
$config['system.performance']['css']['preprocess'] = TRUE;
$config['system.performance']['js']['preprocess']  = TRUE;
$settings['twig_debug']       = FALSE;
$settings['twig_auto_reload'] = FALSE;
$settings['twig_cache']       = TRUE;
SETTINGS_EOF
# Redis cache backend added after module enable (Step 3)
chmod 644 "${SETTINGS_LOCAL}"
echo "  settings.local.php written."

# ─── Step 0.5: Private files directory ───────────────────────────────────────
echo ""
echo "▶ Step 0.5/6: Setting up private files directory..."
PRIVATE_FILES_DIR="/var/www/html/private-files"
mkdir -p "${PRIVATE_FILES_DIR}"
chmod 755 "${PRIVATE_FILES_DIR}"
echo "  Private files directory ready."

# ─── Step 1: Reset database via PDO ──────────────────────────────────────────
echo ""
echo "▶ Step 1/6: Resetting database..."
php -r "
  \$host = getenv('DB_HOST') ?: 'mysql';
  \$port = getenv('DB_PORT') ?: '3306';
  \$user = getenv('DB_USER') ?: 'sityos_user';
  \$pass = getenv('DB_PASS') ?: '';
  \$name = getenv('DB_NAME') ?: 'sityos_prod';
  \$pdo = new PDO(
    \"mysql:host={\$host};port={\$port}\",
    \$user, \$pass,
    [PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false]
  );
  \$pdo->exec(\"DROP DATABASE IF EXISTS \`{\$name}\`\");
  \$pdo->exec(\"CREATE DATABASE \`{\$name}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci\");
  echo 'Database reset OK.' . PHP_EOL;
"

# ─── Step 2: Drupal site install ─────────────────────────────────────────────
echo ""
echo "▶ Step 2/6: Installing Drupal..."

DB_USER_ENC=$(php -r "echo rawurlencode('${DB_USER}');")
DB_PASS_ENC=$(php -r "echo rawurlencode('${DB_PASS}');")

cp "${DRUPAL_ROOT}/sites/default/settings.php" /tmp/settings.php.bak

"${VENDOR_BIN}/drush" site:install standard \
  --root="${DRUPAL_ROOT}" \
  --db-url="mysql://${DB_USER_ENC}:${DB_PASS_ENC}@${DB_HOST:-mysql}:${DB_PORT:-3306}/${DB_NAME}" \
  --account-name="${ADMIN_USER}" \
  --account-pass="${ADMIN_PASS}" \
  --account-mail="${ADMIN_EMAIL}" \
  --site-name="Sityos Automate" \
  --site-mail="admin@sityos.com" \
  --locale=en \
  --yes

cp /tmp/settings.php.bak "${DRUPAL_ROOT}/sites/default/settings.php"

# ─── Step 3: Enable contributed modules ──────────────────────────────────────
echo ""
echo "▶ Step 3/6: Enabling contributed modules..."
"${VENDOR_BIN}/drush" en \
  admin_toolbar \
  admin_toolbar_tools \
  config_split \
  field_group \
  metatag \
  paragraphs \
  pathauto \
  redirect \
  redis \
  token \
  webp \
  language \
  content_translation \
  config_translation \
  locale \
  --root="${DRUPAL_ROOT}" \
  --yes

# Activate Redis as default cache backend now that the module is enabled.
# Production: all bins use Redis except 'form' (session safety).
cat >> "${SETTINGS_LOCAL}" << 'REDIS_EOF'

// ─── Redis cache backend ───────────────────────────────────────────────────
$settings['cache']['default']                    = 'cache.backend.redis';
$settings['cache']['bins']['form']               = 'cache.backend.database';
$settings['cache']['bins']['render']             = 'cache.backend.redis';
$settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.redis';
$settings['cache']['bins']['page']               = 'cache.backend.redis';
REDIS_EOF
echo "  Redis cache backend activated."

# ─── Step 4: Enable custom modules ───────────────────────────────────────────
echo ""
echo "▶ Step 4/6: Enabling Sityos custom modules..."
"${VENDOR_BIN}/drush" en \
  sityos_base \
  sityos_article \
  sityos_tutorial \
  sityos_use_case \
  --root="${DRUPAL_ROOT}" \
  --yes

# ─── Step 5: Languages ───────────────────────────────────────────────────────
echo ""
echo "▶ Step 5/6: Adding languages (es, ca)..."
"${VENDOR_BIN}/drush" language:add es --root="${DRUPAL_ROOT}" --yes || true
"${VENDOR_BIN}/drush" language:add ca --root="${DRUPAL_ROOT}" --yes || true

# ─── Step 6: Config import + cache clear ─────────────────────────────────────
echo ""
echo "▶ Step 6/6: Importing configuration and clearing caches..."
"${VENDOR_BIN}/drush" cim -y --root="${DRUPAL_ROOT}" || \
  echo "  (no config to import or minor warnings — continuing)"
"${VENDOR_BIN}/drush" cr  --root="${DRUPAL_ROOT}"

echo ""
echo "════════════════════════════════════════════════════════"
echo "  ✔  Production install complete!"
echo ""
echo "  Site:  ${SITE_URL}"
echo "  Admin: ${SITE_URL}/user/login"
echo "  User:  ${ADMIN_USER} / ${ADMIN_PASS}"
echo "════════════════════════════════════════════════════════"
