gtm.settings:
  type: config_object
  label: 'Google Tag Manager settings'
  mapping:
    enable:
      type: boolean
      label: 'Enable Google Tag Manager'
    admin-pages:
      type: boolean
      label: 'Display GTM on admin pages'
    admin-disable:
      type: boolean
      label: 'Disable GTM for admin user (uid=1)'
    google-tag:
      type: string
      label: 'GTM Container ID'
